# Generated by Django 3.2.13 on 2023-05-19 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
